### ISSUE TITLE
Note details: transition from full height to half height

### ISSUE THREAD

**Issue by TomaTomoe** [DarthVanger/NeuralNotes#115]
When the following button (bar) is clicked:
![image](https://user-images.githubusercontent.com/19979138/87873030-a9efe400-c9c6-11ea-9761-d7b33c4e9094.png)
The note details should collapse to become the note details preview:
![image](https://user-images.githubusercontent.com/19979138/87873077-f5a28d80-c9c6-11ea-9fa8-1acbbe1ba237.png)
And change arrow direction

**Comment by DarthVanger** [comment]
Changed label to `UI/UX functionality`, because we should store this in redux `state`: something like `noteDetails.isExpanded = true/false`.

In React we will be adding / removing the className.

```
<NoteDetails className={ this.props.isExpanded ? 'is-expanded' : 'is-collapsed' } />
````

In css we will have `transition: ...` for animation when this class is added / removed.
Since this task is small, we can do both React stuff and css together.

**Comment by DarthVanger** [comment]
The design has changed, this functionality was dropped
https://www.figma.com/file/Fp2ZxU4bz0i5LvbOFq8xlY/Neural-Notes-Design-v.0.2.2?node-id=212%3A836
