### ISSUE TITLE
TopBar: hamburger menu (dropdown)

### ISSUE THREAD

**Issue by TomaTomoe** [DarthVanger/NeuralNotes#133]
We have implemented TopBar according to the new design already, but the hamburger menu is black and there is no dropdown shown on click.

Fix the hamburger menu styles and add a dropdown menu.
Move the "Logout" button which is shown in the TopBar on the right into the dropdown which is shown on the hamburger menu click.

[Figma](https://www.figma.com/file/FxmwqO6LRg7tOVXrZqMMG0/Neural-Notes-Design-v.0.3)

![image](https://user-images.githubusercontent.com/6686679/97801349-c564bf00-1c44-11eb-97c9-99137aaef8e3.png)

**Comment by jpalacio0612** [comment]
Hello, my name is Jonathan, I am a fullstack developer, I saw the project in upwork and I am interested in contributing. I have worked with the MERN stack. I was adding Material UI and Material Icons to your project to solve the topbar part and this was the result:

![image](https://user-images.githubusercontent.com/65427911/94224879-29170200-feb9-11ea-9350-8b7bca84f58f.png)


I had to change the class component to function to accept the UI material, but if you are only working with class components we can see how to make it work and for practical purposes add some inline styles, but this should be in a separate file .

```js script
export function TopBarComponent() {
  const classes = useStyles();

  return (
    <div className={classes.root}>
      <AppBar style={{ background: '#272727' }} position="static">
        <Toolbar>
          <IconButton edge="start" className={classes.menuButton} color="inherit" aria-label="menu">
            <MenuIcon />
          </IconButton>
          <Typography style={{ color: '#BB86FC' }} variant="h6" className={classes.title}>
            Neural Notes
          </Typography>
          <CloudUploadIcon style={{ color: '#BB86FC', "margin-right": "10px" }} />
          <SearchIcon />
        </Toolbar>
      </AppBar>
    </div>
  );
}

```

**Comment by DarthVanger** [comment]
@jpalacio0612 Hello Jonathan! That's great! I don't mind changing components from classes to functions.
The upwork job is for the other tasks though, the ones on this board: https://github.com/DarthVanger/NeuralNotes/projects/4 ("hardcore js :)" label).

For the [ui/ux tasks](https://github.com/DarthVanger/NeuralNotes/projects/1) I've got cheaper devs =) because it doesn't require that much of expertise.
We might still benefit from your contributions though, I'll talk with the team.
How much do you charge for this kind of contributions? :)
