### ISSUE TITLE
Proposal: change redux-connected component's names to <ComponentName> instead of <ComponentNameContainer>

### ISSUE THREAD

**Issue by kvoncode** [DarthVanger/NeuralNotes#155]
I think it would be better to change our name conventions a little bit from **ComponentNameContainer** to **ComponentName**. 

This way we:
- do minimal change
- make imports more readable

**Comment by DarthVanger** [comment]
@nick-nikoliuk what do you think?

I believe adding `Container` suffix was done on purpose, in order to make it 100% clear which module is `component` and which module is `container`.

If we remove the `Container` suffix, we will have:
- ComponentNameComponent.js
- ComponentName.js

making it a bit confusing, as it wouldn't be clear what is the difference between `ComponentName` and `ComponentNameComponent`, someone might be confused why do we have 2 files with similar names for 1 component.

While with `Container` suffix it's immediately clear that 1 file is for the redux container, and the other file is for the component itself.

**Comment by kvoncode** [comment]
Ok

**Comment by kvoncode** [comment]
How about
- ComponentName
- ComponentNameUnconnected
?

Vscode have auto renaming feature, so it should be easy to rename even for existing components.
The point is even ComponentNameCom

**Comment by DarthVanger** [comment]
- ComponentName
- ComponentNameUnconnected

Doesn't look better as for me :)

Whenever we want to create a usual react component without getting any values from redux, we'll have have to add the `Unconnected` prefix...

`ComponentNameContainer` and `ComponentNameComponent` looks like the most logical option to me.

I don't mind if we change the naming convention to something popular: maybe there is something in redux styleguide?

If we want to change it from the current custom convention to a new custom convention, I don't really see a point and the options you proposed don't seem to be better than the current one as for me.

But all of them are not perfect :) So if it really bothers you that much - go ahead, change it to your liking...

**Comment by DarthVanger** [comment]
Well... yeah actually I agree that it makes sense to have in JSX something like
```
<App>
    <TopBar />
    <SomePage />
    <BottomBar />
</App>
```
So just component names, without any suffix.
So ok - removing the `Container` suffix makes sense.

**Comment by kvoncode** [comment]
> Well... yeah actually I agree that it makes sense to have in JSX something like
> 
> ```
> <App>
>     <TopBar />
>     <SomePage />
>     <BottomBar />
> </App>
> ```
> 
> So just component names, without any suffix.
> So ok - removing the `Container` suffix makes sense.

Ok, thanks
